- job:
    name: gitsamplejob
    run: playbooks/gitsamplejob.yaml
    parent: base
    nodeset:
      nodes:
        - name: node
          label: centos76
- project:
    check:
      jobs:
        - gitsamplejob
        
