- job:
    name: antbuildjob
    run: playbooks/antbuild.yaml
    parent: base
    nodeset:
      nodes:
        - name: node
          label: ubuntu-bionic
- project:
    check:
      jobs:
        - antbuildjob
    gate:
      jobs:
        - antbuildjob
