- nodeset:
    name: emea
    nodes:
      - name: node_emea
        label: centos76
    groups:
      - name: emea
        nodes:
          - node_emea

- job:
    name: pullrequest_label
    run: playbooks/pullrequest_label.yaml
    parent: base
    pre-run: playbooks/check_location.yaml
    nodeset:
      groups: emea
          
- project:
    pullrequest_label:
      jobs:
        - pullrequest_label
